version: "3.5"

services:
  node:
    container_name: kata-node
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

  mariadb:
    container_name: kata-mariadb
    build:
      context: ./docker/mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lift_pass
      - MYSQL_ROOT_PASSWORD=mysql
